spring.application.name=MotherLink2

# Database configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/MotherLink}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Uhirwashami54.}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Server port (required for Render)
server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=DEBUG