spring.application.name=MotherLink2

#jwt
jwt.secret=wasitthisproblemonlyicannotbelieveforsuerifitwasthisnotYourJustBusinnes
jwt.access-token-expiration=600000
jwt.refresh-token-expiration=86400000

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Server port (required for Render)
server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=DEB